name: deploy website
on:
  push:
    tags:
      - v*

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2
    
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    
    - name: Install Project Dependencies
      run: npm ci

    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli@2.12.34

    - name: Build and Statically Render
      run: gatsby build

    - name: Verify build
      run: ls -la public

    - name: Deploy to S3 preview bucket
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'public/'
