name: publish website
on:
  push:
    tags:
      - v*

jobs:

  predeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test
      env:
        NODE_ENV: production

  deploy:
    needs: predeploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - run: npm ci
    - name: Build and Statically Render
      run: npm run predeploy
      env:
        NODE_ENV: production
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'build/'
